"""Shared typing and helpers for knowledge metadata backends."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any, Protocol


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def iso_cutoff_days_ago(days: int) -> str:
    return (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()


class KnowledgeMetadataStore(Protocol):
    async def ensure_ready(self) -> None: ...
    async def close(self) -> None: ...
    async def add_document(
        self, collection: str, filename: str, chunk_count: int, preview: str = ""
    ) -> None: ...
    async def mark_deleting(self, collection: str, filename: str) -> bool: ...
    async def remove_document(self, collection: str, filename: str) -> None: ...
    async def list_documents(self, collection: str) -> list[dict[str, Any]]: ...
    async def get_deleting_documents(self) -> list[dict[str, Any]]: ...
    async def document_exists(self, collection: str, filename: str) -> bool: ...
    async def create_task(
        self, task_id: str, collection: str, total_files: int, file_tasks: dict[str, dict]
    ) -> dict[str, Any]: ...
    async def get_task(self, task_id: str) -> dict[str, Any] | None: ...
    async def update_task(self, task_id: str, **kwargs: Any) -> None: ...
    async def list_tasks(self, collection: str | None = None) -> list[dict[str, Any]]: ...
    async def recover_stale_tasks(self) -> int: ...
    async def purge_old_tasks(self, max_age_days: int = 7) -> int: ...
    async def get_collection_config(self, collection: str) -> dict[str, Any] | None: ...
    async def set_collection_config(
        self, collection: str, embedding_provider: str, embedding_model: str, embedding_dim: int
    ) -> None: ...
    async def list_all_collection_configs(self) -> list[str]: ...
    async def delete_collection_metadata(self, collection: str) -> None: ...
    async def get_setting(self, key: str, default: str = "") -> str: ...
    async def set_setting(self, key: str, value: str) -> None: ...
    async def get_all_settings(self) -> dict[str, str]: ...
