[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agent_quality_inspect"
version = "2.3.6a1"
description = "Evaluation package that allows benchmarking of agentic AIs from various sources and frameworks by producing statistical results which can be compared across different use cases and datasets."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [
    { name = "Min Pyae Moe", email = "min.pyae.moe@sap.com" },
    { name = "Marcus Duigan", email = "marcus.duigan@sap.com" }
]
dependencies = [
    "numpy==2.2.6",
]

[project.optional-dependencies]
azure-openai = [
    "openai==2.29.0",
    "backoff==2.2.1",
]
litellm = [
    "litellm==1.102.1",
    "openai==2.29.0",
    "backoff==2.2.1",
]

[tool.setuptools.packages.find]
where = ["src"]
include=["agent_inspect", "agent_inspect.*"]

[tool.ruff]
line-length = 100
