from typing import Any, Protocol


class RelationalStore(Protocol):
    async def execute(self, sql: str, params: tuple = ()) -> None: ...
    async def fetchall(self, sql: str, params: tuple = ()) -> list: ...
    async def fetchone(self, sql: str, params: tuple = ()) -> Any: ...
    async def commit(self) -> None: ...
    async def close(self) -> None: ...
