{{- if and .Values.auth.password (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-pgvector.fullname" . }}
  labels:
    {{- include "postgres-pgvector.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.auth.password | quote }}
{{- end }}
