[agent.task_decomposition.model]
platform = "anthropic"
model_name = "claude-opus-4-6"
url = "AZURE_ANTHROPIC_OPENAI_ENDPOINT"
api_key = "AZURE_OPENAI_API_KEY"
temperature = 0.1
max_tokens = 1000


[agent.planner.model]
platform = "anthropic"
model_name = "claude-opus-4-6"
url = "AZURE_ANTHROPIC_OPENAI_ENDPOINT"
api_key = "AZURE_OPENAI_API_KEY"
temperature = 0.1
max_tokens = 5000


[agent.chat.model]
platform = "anthropic"
model_name = "claude-opus-4-6"
url = "AZURE_ANTHROPIC_OPENAI_ENDPOINT"
api_key = "AZURE_OPENAI_API_KEY"
temperature = 0.1
max_tokens = 5000


[agent.plan_controller.model]
platform = "anthropic"
model_name = "claude-opus-4-6"
url = "AZURE_ANTHROPIC_OPENAI_ENDPOINT"
api_key = "AZURE_OPENAI_API_KEY"
temperature = 0.1
max_tokens = 5000


[agent.final_answer.model]
platform = "anthropic"
model_name = "claude-opus-4-6"
url = "AZURE_ANTHROPIC_OPENAI_ENDPOINT"
api_key = "AZURE_OPENAI_API_KEY"
temperature = 0.1
max_tokens = 15000

[agent.code.model]
platform = "anthropic"
model_name = "claude-opus-4-6"
url = "AZURE_ANTHROPIC_OPENAI_ENDPOINT"
api_key = "AZURE_OPENAI_API_KEY"
temperature = 0.1
max_tokens = 3000

[agent.code_planner.model]
platform = "anthropic"
model_name = "claude-opus-4-6"
url = "AZURE_ANTHROPIC_OPENAI_ENDPOINT"
api_key = "AZURE_OPENAI_API_KEY"
temperature = 0.1
max_tokens = 3000

[agent.qa.model]
platform = "anthropic"
model_name = "claude-opus-4-6"
url = "AZURE_ANTHROPIC_OPENAI_ENDPOINT"
api_key = "AZURE_OPENAI_API_KEY"
temperature = 0.1
max_tokens = 4000

[agent.action.model]
platform = "anthropic"
model_name = "claude-opus-4-6"
url = "AZURE_ANTHROPIC_OPENAI_ENDPOINT"
api_key = "AZURE_OPENAI_API_KEY"
temperature = 0.1
max_tokens = 400


[agent.shortlister.model]
platform = "anthropic"
model_name = "claude-opus-4-6"
url = "AZURE_ANTHROPIC_OPENAI_ENDPOINT"
api_key = "AZURE_OPENAI_API_KEY"
temperature = 0.1
max_tokens = 7000
