ERROR_SUMMARIZATION_PROMPT_TEMPLATE = """You are tasked with summarizing the error type in a concise and abstract manner based on the provided explanation. This explanation is generated by a judge model, which evaluates whether the agent’s response satisfies the specified subgoals. In the explanation, a grade of "C" (Complete) indicates success, while "I" (Incomplete) indicates failure.

Your goal is to produce an error type that:
    •	Clearly captures the core failure or issue at an abstract level.
    •	Avoids restating the explanation verbatim.
    •	Is short, specific, and phrased like a category label rather than a long sentence.
    •	Does not include sensitive details or unnecessary context.
    •	If the error type involves tool usage, explicitly include the tool name in the error type.

You will be provided with:
    •	Ground truth subgoals
    •	Judge model’s explanation of the agent’s response

[BEGIN DATA]
***
[Ground Truth Subgoals]: {subgoals}
***
[Explanation]: {explanation}
***
[END DATA]

Please return your output in the following **strict JSON format**:
{{
    "error_type": "<error_type>",
    "explanation": "<explanation>"
}}
"""


MAJORITY_VOTE_PROMPT_TEMPLATE = """You are given multiple independent predictions of the same data row.  
Each prediction includes an error type assigned by a model.  
Your task is to determine the **most probable true error type** using a majority voting approach.

Instructions:
1. Review all provided error types carefully.
2. Group similar or semantically equivalent error types together, even if their wording differs.
3. Count how many times each grouped error type appears.
4. Select the error type with the highest count as the final result.
5. If there is a tie:
   - Prefer the error type that is more specific and informative.
   - If still tied, choose the one most consistent with the majority wording.
6. Output ONLY the most probable error type, without extra commentary.

[BEGIN DATA]
[Error Types]: {error_type_list}
[END DATA]

Please return your output in the following **strict JSON format**:
{{
    "most_probable_error_type": "<most_probable_error_type>"
}}
"""


UNSUPERVISED_CLUSTERING_PROMPT_TEMPLATE = """You are tasked with clustering the following error types based on their semantic similarity. The goal is to group related error types under broader, more abstract categories to reduce redundancy and improve generalization.

Important:
    •	The cluster_label should be primarily grounded in the <subgoals> provided.
    •	Only if you are very certain that an error type is entirely unrelated to the subgoals should you create a new cluster label not derived from them.
    •	Always aim to preserve the subgoal’s intent when naming clusters.

Guidelines:
    •	Error types are not mutually exclusive and may overlap in meaning.
    •	Each cluster should reflect the most abstract and inclusive label that unifies all error types within it.
     •	Do not merge error types referring to different tools into a single cluster.
    •	Clusters involving tool usage must be separated by tool name.
     •	The cluster_label for each tool-related cluster must explicitly include that tool’s name.
    •	Minimize the number of clusters while maintaining clear and meaningful distinctions.
    •	Avoid overly specific wording—cluster labels should be reusable in other contexts where the same subgoal applies.

Cluster label conventions:
    - Write each label as a Title Case noun phrase (3–7 words); no trailing punctuation.
    - State the failure's nature, then its object — e.g. what was missing, incorrect, or incomplete, and in what (a tool call, a parameter, a step, a subgoal).
    - When an error is specific to a tool, name that tool in the label; do not merge errors from different tools into one cluster.
    - Prefer fewer, broader labels; introduce a new distinction only when a real one exists.

[BEGIN DATA]
[Subgoals]: {subgoals}
[Error Types]: {error_types}
[END DATA]

Please return your output in the following strict JSON format:
{{
  "clusters": [
    {{
      "cluster_label": "<generalized_error_type>",
      "error_types": ["<error_type_1>", "<error_type_2>", ...],
      "error_ids": ["<error_id_1>", "<error_id_2>", ...]
    }},
    ...
  ]
}}
"""

SEMI_SUPERVISED_CLUSTERING_PROMPT_TEMPLATE = """You are tasked with clustering error types into categories. You are provided with:
1. A list of predefined error clusters (with descriptions)
2. A list of identified error types from agent failures
3. The subgoals that the agent was supposed to achieve

Your task:
1. For each error type, select the predefined cluster whose description best matches the error's meaning.
2. Every error type MUST be assigned to exactly one predefined cluster.
3. DO NOT create new clusters - only use the predefined clusters provided.

Guidelines:
    • Only assign an error to a predefined cluster when the error is a CLEAR semantic match to that cluster's description. The error's described behavior must genuinely fall within what the cluster description covers.
    • Do NOT assign an error to a cluster based on weak, superficial, or keyword-only association. When in doubt, or when the error does not clearly fit the meaning of any provided cluster, it MUST be assigned to "Unclassified".
    •	Use the "Unclassified" category when you cannot identify a clear agent behavior or decision that caused the failure.
    • Consider the provided subgoals as contextual information when interpreting the errors.
    • Do not omit or duplicate error types.

[BEGIN DATA]
[Predefined Clusters]: {predefined_clusters}
***
[Subgoals]: {subgoals}
***
[Error Types]: {error_types}
***
[END DATA]

Please return your output in the following strict JSON format:
{{
  "clusters": [
    {{
      "cluster_label": "<cluster_label_from_predefined_list>",
      "error_types": ["<error_type_1>", "<error_type_2>", ...],
      "error_ids": ["<error_id_1>", "<error_id_2>", ...],
      "rationale": "<brief explanation of why these errors fit this cluster>"
    }},
    ...
  ]
}}
"""


# Tool Validation Error Classification Templates
# Classifies a single tool validation error into a predefined high-level error category
TOOL_VALIDATION_CLASSIFICATION_PROMPT_TEMPLATE = """You are tasked with classifying a tool call validation error into one of the predefined error categories.

You are provided with:
1. A list of predefined error categories (with descriptions)
2. A tool validation error containing:
   - The expected tool call specification (tool name, parameters, output)
   - The validation explanation describing why the tool call failed

Your task:
Assign this validation error to the MOST appropriate predefined category based on semantic similarity.
DO NOT create new categories - only use the predefined categories provided.

Guidelines:
    •	Choose the category that best matches the root cause of the error
    •	The cluster_label must be exactly as specified in the predefined categories list
    •	Use the "Unclassified" category when you cannot identify a clear agent behavior or decision that caused the failure.
    •	When in doubt between a specific category and "Unclassified", prefer "Unclassified".

[BEGIN DATA]
[Predefined Categories]: {predefined_clusters}
***
[Tool Validation Error]:
Tool: {tool_name}
Expected Parameters: {expected_parameters}
Expected Output: {expected_output}
Validation Explanation: {explanation}
***
[END DATA]

Please return your output in the following strict JSON format:
{{
  "cluster_label": "<selected_category_label_from_predefined_list>",
  "rationale": "<brief explanation of why this error fits the selected category>"
}}
"""
